In [1]:
# Import pandas
import pandas as pd
import numpy as np

In [2]:
# Cargar mis datos como dataframe 
data = pd.read_csv("notes.csv")

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
# Visualizar los primeros 5 renglones de mi dataset
data.head()

    Nombre  nota
0  Araceli     9
1   Manuel     5
2    Pablo     7
3    Iñigo     4
4    Mario     3

In [7]:
# Visualizar head con más renglones
data.head(2)

    Nombre  nota
0  Araceli     9
1   Manuel     5

In [8]:
# Función que me permite ver la estadistica descriptiva de las columnas númericas de mi dataset
data.describe()

            nota
count  13.000000
mean    5.615385
std     2.364264
min     2.000000
25%     4.000000
50%     5.000000
75%     7.000000
max    10.000000

In [10]:
# Yo puedo accesar a cada columna de un dataframe como si fuera un diccionario, 
# en donde el header es la clave y el valor va a ser una lista con todos los datos
# de los renglones de esa respectiva columna

#Accesando a la columna nombre
data["Nombre"]

0      Araceli
1       Manuel
2        Pablo
3        Iñigo
4        Mario
5         Raul
6     Verónica
7        Dario
8        Laura
9       Silvia
10     Eduardo
11      Susana
12       María
Name: Nombre, dtype: object

In [12]:
#Accesando a la columna nota
data["nota"]

0      9
1      5
2      7
3      4
4      3
5      4
6      6
7     10
8      4
9      6
10     2
11     8
12     5
Name: nota, dtype: int64

In [9]:
# USANDO PANDAS
# Calculo de la media
media = data["nota"].mean()
media

5.615384615384615

In [13]:
# Calculo de la mediana
mediana = data["nota"].median()
mediana

5.0

In [19]:
# Calculo de la moda
moda = data["nota"].mode()
print("la moda " + str(moda))

la moda 0    4
Name: nota, dtype: int64

In [20]:
# Calculo del rango 
rango = data["nota"].max() - data["nota"].min()
print(rango)

8

In [21]:
# Calculando la media con numpy
np.mean(data["nota"])

5.615384615384615

In [23]:
np.median(data["nota"])

5.0

In [24]:
# Varianza y desviación estandar de los perritos
peyitos = [600,470,170,430,300]
np.mean(peyitos)

394.0

In [26]:
np.median(peyitos)

430.0

In [27]:
np.var(peyitos)

21704.0

In [28]:
np.std(peyitos)

147.32277488562318